development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: sametut_production
  pool: 5
  username: root
  password: '&7Qo.;[nW4$^7[n'
  socket: /var/run/mysqld/mysqld.sock
